language: python
notification:
    email: false

python:
  - "2.6"
  - "2.7"

before_install:
  - pushd .
  - sudo apt-get update -qq
  - sudo apt-get install -y curl erlang
  - git clone https://github.com/discoproject/disco.git /tmp/disco
  - cd /tmp/disco && git checkout 0.5 && sudo make install
  - cd lib && pip install .
  - popd

install:
  - "pip install mock"
  - "pip install ."  
  
script: nosetests
